### ISSUE TITLE
Shield bar doesn't stop flashing randomly

### ISSUE THREAD

**Issue by atomical** [foonull/HaloMD#25]
Sometimes the shield bar won't stop flashing. I've encountered this with Bloodgulch and Bigass. Others have encountered this as well. This only started happening after the latest update.

**Comment by ghost** [comment]
This appears to be an issue with SAPP's spawn protection system, as I've managed to reproduce it on both the Mac and Windows versions of Halo PC (the full version of the game), thus it has absolutely nothing to do with the HaloMD update.

The issue occurs when a player has been hit by an explosive or a sniper rifle headshot during SAPP's spawn protection time. Because the player's shields did not really get reduced, the server won't inform the client that they came back up.
